/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShoppingListsIndexRouteImport } from './routes/shopping-lists.index'
import { Route as FamiliesIndexRouteImport } from './routes/families/index'
import { Route as ShoppingListsIdRouteImport } from './routes/shopping-lists.$id'
import { Route as FamiliesFamilyIdRouteImport } from './routes/families/$familyId'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListsIndexRoute = ShoppingListsIndexRouteImport.update({
  id: '/shopping-lists/',
  path: '/shopping-lists/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesIndexRoute = FamiliesIndexRouteImport.update({
  id: '/families/',
  path: '/families/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListsIdRoute = ShoppingListsIdRouteImport.update({
  id: '/shopping-lists/$id',
  path: '/shopping-lists/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliesFamilyIdRoute = FamiliesFamilyIdRouteImport.update({
  id: '/families/$familyId',
  path: '/families/$familyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/logout': typeof LogoutRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/shopping-lists/$id': typeof ShoppingListsIdRoute
  '/families/': typeof FamiliesIndexRoute
  '/shopping-lists/': typeof ShoppingListsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/logout': typeof LogoutRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/shopping-lists/$id': typeof ShoppingListsIdRoute
  '/families': typeof FamiliesIndexRoute
  '/shopping-lists': typeof ShoppingListsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/logout': typeof LogoutRoute
  '/families/$familyId': typeof FamiliesFamilyIdRoute
  '/shopping-lists/$id': typeof ShoppingListsIdRoute
  '/families/': typeof FamiliesIndexRoute
  '/shopping-lists/': typeof ShoppingListsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/logout'
    | '/families/$familyId'
    | '/shopping-lists/$id'
    | '/families/'
    | '/shopping-lists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/logout'
    | '/families/$familyId'
    | '/shopping-lists/$id'
    | '/families'
    | '/shopping-lists'
  id:
    | '__root__'
    | '/'
    | '/error'
    | '/logout'
    | '/families/$familyId'
    | '/shopping-lists/$id'
    | '/families/'
    | '/shopping-lists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorRoute: typeof ErrorRoute
  LogoutRoute: typeof LogoutRoute
  FamiliesFamilyIdRoute: typeof FamiliesFamilyIdRoute
  ShoppingListsIdRoute: typeof ShoppingListsIdRoute
  FamiliesIndexRoute: typeof FamiliesIndexRoute
  ShoppingListsIndexRoute: typeof ShoppingListsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-lists/': {
      id: '/shopping-lists/'
      path: '/shopping-lists'
      fullPath: '/shopping-lists/'
      preLoaderRoute: typeof ShoppingListsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/': {
      id: '/families/'
      path: '/families'
      fullPath: '/families/'
      preLoaderRoute: typeof FamiliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-lists/$id': {
      id: '/shopping-lists/$id'
      path: '/shopping-lists/$id'
      fullPath: '/shopping-lists/$id'
      preLoaderRoute: typeof ShoppingListsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/families/$familyId': {
      id: '/families/$familyId'
      path: '/families/$familyId'
      fullPath: '/families/$familyId'
      preLoaderRoute: typeof FamiliesFamilyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorRoute: ErrorRoute,
  LogoutRoute: LogoutRoute,
  FamiliesFamilyIdRoute: FamiliesFamilyIdRoute,
  ShoppingListsIdRoute: ShoppingListsIdRoute,
  FamiliesIndexRoute: FamiliesIndexRoute,
  ShoppingListsIndexRoute: ShoppingListsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
